* fyshpkgs
*f*​e​*y*​or​*sh*'s *p*​ac​*k*​a​*g*​e​*s*

* Packages
** Mathematica
The Mathematica installer can be scripted on Linux, but it's a lost cause on Darwin. That being said, we can simply install it, add it to the Nix store, and then only use it when we want it. Plus, we can add some goodies like symlinking ~math~ like on Linux (although it conflicts with the fish builtin of the same name, ~wolfram~ can be used instead) and the inclusion of ~mash.pl~ to be able to use Mathematica with org-babel (per [[https://rgoswami.me/posts/org-mathematica/][this article]]).

The only weird thing is that ~Mathematica~ won't run properly as a symlink; I used ~makeWrapper~ instead, which itself ought to be replaced by ~makeBinaryWrapper~, but I think it's currently broken on Darwin or something. Oh well.

* TODO Setup
1. +Click on [[https://github.com/nix-community/nur-packages-template/generate][Use this template]] to start a repo based on this template. (Do _not_ fork it.)+
2. +Add your packages to the [[./pkgs][pkgs]] directory and to [[./default.nix][default.nix]].+
   * Remember to mark the broken packages as `broken = true;` in the `meta`
     attribute, or travis (and consequently caching) will fail!
   * Library functions, modules and overlays go in the respective directories
3. Choose your CI: Depending on your preference you can use github actions (recommended) or [[https://travis-ci.com][Travis ci]].
   - Github actions: Change your NUR repo name and optionally add a cachix name in [[./.github/workflows/build.yml][.github/workflows/build.yml]] and change the cron timer to a random value as described in the file.
   - Travis ci: Change your NUR repo name and optionally your cachix repo name in [[./.travis.yml][.travis.yml]]. Than enable travis in your repo. You can add a cron job in the repository settings on travis to keep your cachix cache fresh
4. Change your travis and cachix names on the README template section and delete the rest
5. [[https://github.com/nix-community/NUR#how-to-add-your-own-repository][Add yourself to NUR]]
